---
###### node_version: (Node variable) should be made explicit on the main playbook

# - name: Node.js | Checking installed version of node.js
#   shell: /usr/bin/test "$(node -v)" = "{{ vnode_version }}"
#   register: result
#   ignore_errors: True

- name: Node.js | Fetching node.js source
  action: get_url url=http://nodejs.org/dist/v{{ node_version }}/{{ node_tarball }} dest=/tmp/
  sudo: yes
  # when_failed: False

- name: Node.js | Unpack node.js tarball
  shell: tar zxf {{ node_tarball }} chdir=/tmp/
  # when: we_cool != node_version
  ignore_errors: true

- name: Take Ownership of Node Folder
  shell: /bin/chown -hR deploy:deploy  /tmp/{{ node_prefix }}/
  sudo: yes

- name: Node.js | Configure
  shell: /usr/bin/python ./configure --prefix={{ node_path }} chdir=/tmp/{{ node_prefix }}
  # when: we_cool != 0

- name: Node.js | Make
  shell: /usr/bin/make chdir=/tmp/{{ node_prefix }}/
  # when: we_cool != 0

- name: Node.js | Make install
  shell: /usr/bin/make install chdir=/tmp/{{ node_prefix }}/
  sudo: yes
  # when: we_cool != 0
